Course.MovieWebUI/Models/Category.cs
namespace Course.MovieWebUI.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Course.MovieWebUI/Models/ErrorViewModel.cs
namespace Course.MovieWebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Course.MovieWebUI/Models/Movie.cs
namespace Course.MovieWebUI.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }

        public int CategoryId { get; set; }
    }
}

Course.MovieWebUI/Models/MovieCategoryModel.cs
namespace Course.MovieWebUI.Models
{
    public class MovieCategoryModel
    {
        public Movie Movie { get; set; }
        public IEnumerable<Movie> Movies { get; set; }
        public IEnumerable<Category> Categories { get; set; }
    }
}

Course.MovieWebUI/Controllers/HomeController.cs
using Course.MovieWebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Course.MovieWebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }       

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Course.MovieWebUI/Controllers/MovieController.cs
using Course.CategoryWebUI.Repository;
using Course.MovieWebUI.Models;
using Course.MovieWebUI.Repository;
using Microsoft.AspNetCore.Mvc;

namespace Course.MovieWebUI.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult Index()
        {
            var list = Repository.MovieRepository.Movies;
            var catlist = CategoryRepository.Categories;

            CategoryMovieVM categoryMovieVM = new CategoryMovieVM();
            categoryMovieVM.Movies= list;
            categoryMovieVM.Categories= catlist;

            return PartialView(categoryMovieVM);
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Detail(int id)
        {
            Movie movie=Repository.MovieRepository.GetMovieById(id);

            return View(movie);
        }


        public IActionResult List()
        {
            var list = Repository.MovieRepository.Movies;
            return View(list);
        }

        public IActionResult PartialMovies()
        {
            var list = Repository.MovieRepository.Movies;
            return PartialView(list);
        }
        public IActionResult PartialMenu()
        {
            return PartialView();
        }

        
    }
}

Course.MovieWebUI/ViewComponents/CategoryViewComponent.cs
using Course.CategoryWebUI.Repository;
using Microsoft.AspNetCore.Mvc;

namespace Course.MovieWebUI.ViewComponents
{
    public class CategoryViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View(CategoryRepository.Categories);
        }
    }
}

Course.MovieWebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Course.MovieWebUI/Views/Movie/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

Course.MovieWebUI/Views/Movie/Detail.cshtml
@model Movie

@{
    ViewData["Title"] = "Detail";
}

<div class="card-group">
  

        <div class="card">
            <img class="card-img-top" src="@Model.ImageUrl" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">
                <a asp-action="Detail" asp-controller="Movie" asp-route-id="@Model.Id">
                    @Model.Name
                    </a>
                </h5>
            <p class="card-text">@Model.Description</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
        </div>
    
</div>

Course.MovieWebUI/Views/Movie/Index.cshtml
@using Course.MovieWebUI.Repository;
@model CategoryMovieVM
@{
    ViewData["Title"] = "Index";
}

<div class="row">

    <div class="col-md-3">
        @*@Html.Partial("PartialMenu",Model.Categories)*@
        @*<partial name="PartialMovies" model="Model.Categories" />*@
        @await Component.InvokeAsync("Category")
    </div>


    <div class="col-md-9">

        @*@Html.Partial("PartialMovies",Model)*@
        <partial name="PartialMovies" model="Model.Movies" />
       
    </div>
</div>

Course.MovieWebUI/Views/Movie/List.cshtml
@{
    ViewData["Title"] = "List";
}



<div class="col-md-3">
  
</div>


<div class="col-md-9">

<div class="card-group">

    


</div>

</div>

Course.MovieWebUI/Views/Movie/PartialMenu.cshtml
@using Course.MovieWebUI.Repository;
@model CategoryMovieVM

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<ul class="list-group">

    @foreach (var item in Model.Categories)
    {
        
    <li class="list-group-item active">@item.Name</li>
    }
   @* <li class="list-group-item">Dapibus ac facilisis in</li>
    <li class="list-group-item">Morbi leo risus</li>
    <li class="list-group-item">Porta ac consectetur ac</li>
    <li class="list-group-item">Vestibulum at eros</li>*@
</ul>

Course.MovieWebUI/Views/Movie/PartialMovies.cshtml
@model List<Movie>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<div class="card-group">
    @foreach (var item in Model)
    {

        <div class="card">
            <img class="card-img-top" src="@item.ImageUrl" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">
                    <a asp-action="Detail" asp-controller="Movie" asp-route-id="@item.Id">
                        @item.Name
                    </a>
                </h5>
                <p class="card-text">@item.Description</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
        </div>
    }
</div>

Course.MovieWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Course.MovieWebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Course.MovieWebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Course.MovieWebUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Course.MovieWebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>